//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_01LinhKienSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int ID { get; set; }
        public string HOTEN { get; set; }
        public string PASSWORD { get; set; }
        public string EMAIL { get; set; }
        public string SDT { get; set; }
        public Nullable<int> ID_TAIKHOAN_ADMIN { get; set; }
    
        public virtual TaiKhoan_Admin TaiKhoan_Admin { get; set; }
    }
}
