//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_01LinhKienSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChiTietDanhMuc()
        {
            this.SanPham = new HashSet<SanPham>();
        }
    
        public int MaChiTiet { get; set; }
        public int MaDanhMuc { get; set; }
        public string TenChiTiet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPham { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}
