//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_01LinhKienSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int ID { get; set; }
        public string TENSP { get; set; }
        public Nullable<double> GIAGOC { get; set; }
        public Nullable<double> GIAHT { get; set; }
        public string IMG { get; set; }
        public Nullable<int> IDLOAISP { get; set; }
        public Nullable<int> MaChiTiet { get; set; }
    
        public virtual ChiTietDanhMuc ChiTietDanhMuc { get; set; }
        public virtual LoaiSP LoaiSP { get; set; }
    }
}
