//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_01LinhKienSP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTin_GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThongTin_GioHang()
        {
            this.LishSuMuaHnag = new HashSet<LishSuMuaHnag>();
        }
    
        public int ID { get; set; }
        public string TENSP { get; set; }
        public double GIAGOC { get; set; }
        public double GIAHT { get; set; }
        public string IMG { get; set; }
        public Nullable<int> IDGIOHANG { get; set; }
        public Nullable<int> SOLUONG { get; set; }
    
        public virtual GioHang GioHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LishSuMuaHnag> LishSuMuaHnag { get; set; }
    }
}
